"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import Navigation from "@/app/components/Navigation";
import type { Verdict } from "@/mock/data";

export default function SubmissionStatusPage() {
  const [state, setState] = useState<Verdict>("Pending");
  useEffect(() => { const timers = [setTimeout(() => setState("Running"), 1400), setTimeout(() => setState("Accepted"), 3500)]; return () => timers.forEach(clearTimeout); }, []);
  const progress = state === "Pending" ? 0 : state === "Running" ? 58 : 100;
  return <><Navigation /><main className="pt-20 max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8"><Link href="/problems/1" className="text-xs font-mono text-kjtext-muted hover:text-kjprimary">← Return to problem</Link><div className="mt-6 flex flex-col sm:flex-row sm:justify-between sm:items-end gap-4"><div><p className="text-xs uppercase tracking-widest font-mono text-kjprimary">Submission monitor</p><h1 className="text-3xl font-mono font-bold text-kjtext mt-2">Submission #1042</h1></div><span className={`font-mono text-sm ${state === "Accepted" ? "text-green-400" : "text-yellow-400"}`}>{state === "Accepted" ? "✓ ACCEPTED" : `◌ ${state.toUpperCase()}`}</span></div><section className="mt-8 bg-kjsurface border border-kjborder rounded-lg p-6"><div className="grid sm:grid-cols-4 gap-5 text-xs font-mono"><div><p className="text-kjtext-muted">PROBLEM</p><p className="text-kjtext mt-2">Two Sum</p></div><div><p className="text-kjtext-muted">LANGUAGE</p><p className="text-kjtext mt-2">Python</p></div><div><p className="text-kjtext-muted">SUBMITTED</p><p className="text-kjtext mt-2">18 Aug 2026, 11:42</p></div><div><p className="text-kjtext-muted">VERDICT</p><p className="text-green-400 mt-2">{state === "Accepted" ? "Accepted" : "Evaluating"}</p></div></div><div className="mt-10"><div className="flex justify-between text-xs font-mono text-kjtext-muted mb-2"><span>TEST CASE PROGRESS</span><span>{state === "Accepted" ? "12 / 12" : state === "Running" ? "7 / 12" : "queued"}</span></div><div className="h-2 rounded bg-kjbg overflow-hidden"><div className="h-full bg-kjprimary transition-all duration-700" style={{ width: `${progress}%` }} /></div></div></section><div className="grid sm:grid-cols-3 gap-4 mt-4"><div className="bg-kjsurface border border-kjborder rounded-lg p-5"><p className="text-xs font-mono text-kjtext-muted">RUNTIME</p><p className="text-2xl font-mono text-kjtext mt-2">{state === "Accepted" ? "0.42 s" : "--"}</p></div><div className="bg-kjsurface border border-kjborder rounded-lg p-5"><p className="text-xs font-mono text-kjtext-muted">MEMORY</p><p className="text-2xl font-mono text-kjtext mt-2">{state === "Accepted" ? "18 MB" : "--"}</p></div><div className="bg-kjsurface border border-kjborder rounded-lg p-5"><p className="text-xs font-mono text-kjtext-muted">QUEUE STATE</p><p className="text-2xl font-mono text-kjprimary mt-2">{state}</p></div></div><p className="mt-6 text-xs font-mono text-kjtext-muted">Mock judge progression: Pending → Running → Accepted.</p></main></>;
}
